include:
  - file: .rule-template.yml
    project: zarebin-public/cicd-template
  - file: .scan-template.yml
    project: zarebin-public/cicd-template
 
 
 

 
build_web_ui_dev:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  only:
    refs:
      - dev
  script:
    - export IMAGE="docker.mci.dev/darkube/mci/web-ui"
    - "darkube build -f ./Dockerfile --push -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_REF_SLUG
      --workdir . "
 
build_web_ui_stage:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  extends:
    - .staging_build
  script:
    - export IMAGE="docker.mci.dev/darkube/mci/web-ui"
    - "darkube build -f ./Dockerfile --push -t $IMAGE:$CI_COMMIT_TAG -t $IMAGE:$CI_COMMIT_REF_SLUG
      --workdir . "
 
web-ui_container_scan:
  extends:
    - .container_scan
  variables:
    IMAGE: docker.mci.dev/darkube/mci/web-ui     
   
     
deploy_web_ui_dev:
  only:
    refs:
    - dev
  stage: deploy
  trigger:
    branch: master
    project: mse/fajr/fajr-ops
  variables:
    APP_NAME: wheel_of_fortune
    CHART_YAML_PATH: values.yaml
    ENV: dev
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
 
deploy_web_ui_stage:
  extends:
    - .staging_deploy
  stage: deploy
  trigger:
    branch: master
    project: mse/fajr/fajr-ops
  variables:
    APP_NAME: wheel_of_fortune
    CHART_YAML_PATH: values.yaml
    ENV: stage
    IMAGE_TAG: $CI_COMMIT_TAG